name = "trace-backend"
main = "worker.js"
compatibility_date = "2026-08-26"

[vars]
# Replace this with your actual InfinityFree URL
ALLOWED_ORIGIN = "https://trace.kesug.com"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "98a5287971e74af499884d52c77e02d8"
